### ISSUE TITLE
I Have Error When Im Running This App

### ISSUE THREAD

**Issue by amirkhh** [poulter7/backgammon-js#8]
Hello,
When im running this app with this code: (`node app.js`) i have this error:

`
TypeError: app.configure is not a function
    at loadApp (C:\Users\Administrator\backgammon\src\server.js:61:6)
at Object.start (C:\Users\Administrator\backgammon\src\server.js:189:21)
    at Object.<anonymous> (C:\Users\Administrator\backgammon\app.js:7:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
`

please help me to fix this error and run app.

thanks a lot.

**Comment by poulter7** [comment]
I guess this is an issue with this code not being compatible with newer versions of node.
I'm a bit busy at the moment, but I'll look at this near the end of the week.

**Comment by amirkhh** [comment]
Thanks a lot, Im Waiting.

**Comment by poulter7** [comment]
The game is playable again, but this raises a few other issues, which you're welcome to take a look into.

**Comment by poulter7** [comment]
I've added #9 #10

**Comment by amirkhh** [comment]
Thanks a lot @poulter7 , bugs fixed.

**Comment by poulter7** [comment]
I guess the issues in the rendering are apronably caused by d3 changes though. Maybe I can force an old version and get away with it, or migrate to the latest.
